In [1]:
# Question 1.1
import numpy as np

arr1 = np.arange(5, 26)
print(arr1)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [2]:
# Question 1.2
arr2 = np.random.randint(10, 51, size=(3, 4))
print(arr2)

[[36 29 21 29]
 [21 39 31 36]
 [50 28 30 42]]


In [3]:
# Question 2.1
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data type:", arr1.dtype)

Shape: (21,)
Size: 21
Data type: int64


In [4]:
# Question 2.2
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)

Shape: (3, 4)
Size: 12
Data type: int64


In [5]:
# Question 3.1
array1 = np.array([2, 4, 6, 8, 10])
array2 = np.array([1, 3, 5, 7, 9])
print("Array1:", array1)
print("Array2:", array2)

Array1: [ 2  4  6  8 10]
Array2: [1 3 5 7 9]


In [6]:
# Question 3.2
print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)
print("Division:", array1 / array2)

Addition: [ 3  7 11 15 19]
Subtraction: [1 1 1 1 1]
Multiplication: [ 2 12 30 56 90]
Division: [2.         1.33333333 1.2        1.14285714 1.11111111]


In [7]:
# Question 4.1
arr3 = np.arange(1, 10).reshape(3, 3)
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Question 4.2
print(arr3 * 5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [9]:
# Question 5.1
arr4 = np.arange(10, 26).reshape(4, 4)
print(arr4)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [10]:
# Question 5.2
print("Second row:", arr4[1])
print("Last column:", arr4[:, -1])

Second row: [14 15 16 17]
Last column: [13 17 21 25]


In [11]:
# Question 5.3
arr4[0] = 0
print(arr4)

[[ 0  0  0  0]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [12]:
# Question 6.1
arr5 = np.random.randint(20, 41, 10)
print(arr5)

[31 28 34 35 39 21 38 38 27 40]


In [13]:
# Question 6.2
print(arr5[arr5 > 30])

[31 34 35 39 38 38 40]


In [14]:
# Question 7.1
arr6 = np.arange(11, 23)
print(arr6)

[11 12 13 14 15 16 17 18 19 20 21 22]


In [15]:
# Question 7.2
reshaped = arr6.reshape(3, 4)
print(reshaped)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [16]:
# Question 8.1
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


In [17]:
# Question 8.2
print("Matrix multiplication:\n", np.dot(A, B))
print("Transpose of A:\n", A.T)

Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [18]:
# Question 9.1
arr7 = np.random.randint(10, 61, 15)
print(arr7)

[15 23 51 22 60 54 14 45 36 40 40 33 20 47 57]


In [19]:
# Question 9.2
print("Mean:", np.mean(arr7))
print("Median:", np.median(arr7))
print("Standard deviation:", np.std(arr7))

Mean: 37.13333333333333
Median: 40.0
Standard deviation: 14.912485447510827


In [20]:
# Question 10.1
A = np.array([[2, 1, 3], [0, 5, 6], [7, 8, 9]])
print("Matrix A:\n", A)

Matrix A:
 [[2 1 3]
 [0 5 6]
 [7 8 9]]


In [21]:
# Question 10.2
det = np.linalg.det(A)
inv = np.linalg.inv(A)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Determinant:", det)
print("Inverse:\n", inv)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Determinant: -68.99999999999996
Inverse:
 [[ 0.04347826 -0.2173913   0.13043478]
 [-0.60869565  0.04347826  0.17391304]
 [ 0.50724638  0.13043478 -0.14492754]]
Eigenvalues: [15.45215427  2.40475147 -1.85690573]
Eigenvectors:
 [[-0.22453607 -0.55941438 -0.38300969]
 [-0.48513596  0.7607706  -0.60830181]
 [-0.84511931 -0.3290648   0.69517803]]


In [22]:
# Question 11.1
positions = np.array([[0,0], [2,3], [4,7], [7,10], [10,15]])
dist = np.linalg.norm(positions[-1] - positions[0])
print("Euclidean distance:", dist)

Euclidean distance: 18.027756377319946


In [23]:
# Question 11.2
steps = np.diff(positions, axis=0)
total_distance = np.sum(np.linalg.norm(steps, axis=1))
print("Total distance traveled:", total_distance)

Total distance traveled: 18.151279812428157
